apiVersion: v1
kind: Pod
metadata:
  name: movie-db
  labels:
    component: web
spec:
    containers:
    - name: web
      image: maheshgudi/moviedb
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 8000