version: '3.3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - ALLOWED_HOSTS=127.0.0.1
    volumes: 
      - .:/moviedb
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=moviedb
    ports:
      - "5432:5555"
