openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/allmovies/:
    get:
      operationId: listMovies
      description: API to get all movies in the database.
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
  /api/movie/{movie_id}/:
    get:
      operationId: RetrieveMovieDetail
      description: API only for admin to get, delete and update the movie info
      parameters:
      - name: movie_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    post:
      operationId: CreateMovieDetail
      description: API only for admin to get, delete and update the movie info
      parameters:
      - name: movie_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    put:
      operationId: UpdateMovieDetail
      description: API only for admin to get, delete and update the movie info
      parameters:
      - name: movie_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    delete:
      operationId: DestroyMovieDetail
      description: API only for admin to get, delete and update the movie info
      parameters:
      - name: movie_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: ''
  /api/movie/:
    get:
      operationId: listMovieDetails
      description: API only for admin to get, delete and update the movie info
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
    post:
      operationId: CreateMovieDetail
      description: API only for admin to get, delete and update the movie info
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    put:
      operationId: UpdateMovieDetail
      description: API only for admin to get, delete and update the movie info
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    delete:
      operationId: DestroyMovieDetail
      description: API only for admin to get, delete and update the movie info
      parameters: []
      responses:
        '204':
          description: ''
  /api/search/:
    get:
      operationId: listSearchMovies
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
  /api/register/:
    post:
      operationId: CreateRegister
      description: API to register user and generate token
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
