apiVersion: apps/v1
kind: Deployment
metadata: 
  name: moviedb-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: maheshgudi/moviedb
          ports:
          - containerPort: 8000
          resources:
            requests:
              cpu: "250m"